---
- hosts: infra
  remote_user: edureka
  vars:
    SHELL_RUN_PATH: "/home/edureka/devops/"

  tasks:
    - name: start-date-time
      shell: |
        echo "$(date +%s)" > starttimefile
      args:
        chdir: "{{ SHELL_RUN_PATH }}"

    - name: sleep for random time (less than 5 seconds)
      shell: sleep $(shuf -i 1-4 -n 1)

    - name: finish-date-time
      shell: |
        finishtime=$(date +%s)
        starttime=`cat starttimefile`
        DIFF=$(( $finishtime - $starttime ))
        echo "Playbook ran for $((DIFF/60)) mins and $((DIFF%60)) seconds"
        rm starttimefile
      args:
        chdir: "{{ SHELL_RUN_PATH }}"
      register: DURATION

    - name: Print Duration Information
      debug:
        msg: "{{ DURATION.stdout }}"
