---
- hosts: infra  
  remote_user: edureka
  tasks:
    - name: test connection(s)
      ping:   
    - name: copy file(s)
      copy: 
        src: "/home/edureka/devops/copy1" 
        dest: "/home/edureka/devops/"
        owner: edureka
        group: edureka
        mode: 0644
      copy: 
        src: "/home/edureka/devops/copy2" 
        dest: "/home/edureka/devops/"
        owner: edureka
        group: edureka
        mode: 0644
    - name: get access control list
      acl:
        path: "/home/edureka/devops/copy2"
      register: acl_info
    - name: debug info is printed
      debug: 
        var: acl_info
        verbosity: 2
    
