---
- name: Install tree on nodes
  hosts: ubuntu-nodes,centos-nodes
  become: yes

  tasks:
    - name: install tree utility on ubuntu
      apt: 
        name: tree
        state: present
      tags: installTreeOnUbuntu
      when: ansible_distribution == "Ubuntu"
   
    - name: install tree utility on centos
      yum:
        name: tree
        state: present
      tags: installTreeOnCentos
      when: ansible_distribution == "CentOS"
