---

- hosts: all  
  remote_user: edureka
  vars: 
    APP_HOME_DIR: "/home/edureka/devops"
    APP_NAME: "devops-web-maven"
  #  service_name: "devops-web-maven-init-script"

  tasks:
    - name: test connection(s)
      ping: 

    - name: Host Uptime
      shell: /usr/bin/uptime
      register: result
      when: ansible_os_family == "Debian"

    - name: Host Uptime Display
      debug:
        msg:
          - "msg1 = {{ result.stdout_lines[0] }}"
      when: ansible_os_family == "Debian"

    - name: Get springboot app PID
      shell: ps fax | grep java | grep -v grep | grep {{ APP_NAME }}.jar |awk '{print $1}'
      register: running_pid

    - name: Print Application PID
      debug:
        var: running_pid.stdout
        verbosity: 2
      
    - name: Stop springboot app (using PID)
      shell: kill -9 {{ running_pid.stdout }}
      notify: Start springboot app


    #- name: Stop {{ service_name }} Service
    #  service: name={{ service_name }} state=stopped
    #  when: ansible_os_family == "Debian"
    #  notify: Start {{ service_name }} Service

    - name: sleep for random time (less than 10 seconds)
      shell: sleep $(shuf -i 2-10 -n 1)
      
    - name: get access control list
      acl: path="/home/edureka/devops"
      register: acl_info
      when: ansible_os_family == "Debian"

    - name: access control info is printed
      debug: 
        var: acl_info.acl
        verbosity: 2    
      when: ansible_os_family == "Debian"

  handlers:
    - name: Start springboot app
      shell: nohup java -jar {{APP_NAME}}.jar > {{ APP_HOME_DIR }}/log-{{ APP_NAME }}.out 2>&1 &
      args:
        chdir: "{{ APP_HOME_DIR }}"  

    #- name: Start {{ service_name }} Service
    #  service: name={{ service_name }} state=started
    #  when: ansible_os_family == "Debian"
