---

- hosts: all  
  remote_user: edureka
  vars: 
    service_name: "devops-web-maven-init-script"

  tasks:
    - name: test connection(s)
      ping: 

    - name: Host Uptime
      shell: /usr/bin/uptime
      register: result
      when: ansible_os_family == "Debian"

    - name: Host Uptime Display
      debug:
        msg:
          - "msg1 = {{ result.stdout_lines[0] }}"
      when: ansible_os_family == "Debian"

    - name: Stop {{ service_name }} Service
      service: name={{ service_name }} state=stopped
      when: ansible_os_family == "Debian"

    - name: sleep for random time (less than 10 seconds)
      shell: sleep $(shuf -i 2-10 -n 1)
  
    - name: Start {{ service_name }} Service
      service: name={{ service_name }} state=started
      when: ansible_os_family == "Debian"
    
    - name: get access control list
      acl: path="/home/edureka/devops"
      register: acl_info
      when: ansible_os_family == "Debian"

    - name: access control info is printed
      debug: 
        var: acl_info.acl
        verbosity: 2    
      when: ansible_os_family == "Debian"

